# Generated by Django 6.0.3 on 2026-03-26 00:22

import client.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text='8–15 digits. You can include spaces, +, or dashes (e.g. 01xxxxxxxxx or +20 1xx …).', max_length=20, validators=[client.validators.validate_phone_number]),
        ),
    ]
